from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def generate_pdf(employee, prediction, analysis):
    """
    Generate a professional Employee Attrition PDF Report.
    """

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30,
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER
    title_style.textColor = colors.darkblue

    heading_style = styles["Heading2"]
    normal_style = styles["BodyText"]

    story = []

    # =====================================================
    # TITLE
    # =====================================================

    story.append(
        Paragraph(
            "Employee Attrition Prediction Report",
            title_style,
        )
    )

    story.append(
        Paragraph(
            "<b>XGBoost Machine Learning Model</b>",
            normal_style,
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"<b>Generated On:</b> "
            f"{datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            normal_style,
        )
    )

    story.append(Spacer(1, 20))

    # =====================================================
    # EMPLOYEE DETAILS
    # =====================================================

    story.append(
        Paragraph(
            "Employee Information",
            heading_style,
        )
    )

    employee_table = [["Field", "Value"]]

    for key, value in employee.items():
        employee_table.append([str(key), str(value)])

    table = Table(
        employee_table,
        colWidths=[180, 250],
    )

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ]
        )
    )

    story.append(table)

    story.append(Spacer(1, 20))

    # =====================================================
    # PREDICTION SUMMARY
    # =====================================================

    story.append(
        Paragraph(
            "Prediction Summary",
            heading_style,
        )
    )

    story.append(
        Paragraph(
            prediction,
            normal_style,
        )
    )

    story.append(Spacer(1, 20))

    # =====================================================
    # AI ANALYSIS
    # =====================================================

    story.append(
        Paragraph(
            "AI HR Analysis",
            heading_style,
        )
    )

    analysis = analysis.replace("\n", "<br/>")

    story.append(
        Paragraph(
            analysis,
            normal_style,
        )
    )

    story.append(Spacer(1, 20))

    # =====================================================
    # FOOTER
    # =====================================================

    story.append(
        Paragraph(
            "<b>Generated By:</b> Employee Attrition Prediction System",
            normal_style,
        )
    )

    story.append(
        Paragraph(
            "<b>AI Engine:</b> Google Gemini + XGBoost",
            normal_style,
        )
    )

    story.append(
        Paragraph(
            "<b>Developer:</b> B. Yashwanth",
            normal_style,
        )
    )

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf